---
title: Sunday data/statistics link roundup (5/19/2013)
author: Jeff Leek
date: '2013-05-19'
output:
  distill::distill_article:
    self_contained: no
---

  1. This is a [  1. This is a](http://camdp.com/blogs/21st-century-problems) on 20th versus 21st century problems and the rise of the importance of empirical science. I particularly like the discussion of what it means to be a "solved" problem and how that has changed.
  2. [A discussion](http://www.sciencemag.org/content/340/6134/787.full) in Science about the (arguably) most important statistics among academics, the impact factor and h-index. This comes on the heels of the [San Francisco Declaration of Research Assessment](http://am.ascb.org/dora/). I like the idea that we should focus on evaluating science for its own merit rather than focusing on summaries like impact factor. But I worry that the "gaming" people are worried about with quantitative numbers like IF will be replaced with "politicking" if it becomes too qualitative. (via Rafa)
  3. A [write-up](http://blogs.telegraph.co.uk/news/tomchiversscience/100217094/depressing-just-nine-per-cent-of-britons-trust-stats-over-our-own-experience-though-most-of-us-wont-believe-that/) about a survey  in Britain that suggests people don't believe statistics (surprise!). I think this is symptomatic of a bigger issue which is being raised over and over. In the era when scientific problems don't have deterministic solutions how do we determine if a problem has been solved? There is no good answer for this yet and it threatens to undermine a major fraction of the scientific enterprise going forward.
  4. Businesses are confusing [data analysis and big data](http://qz.com/81661/most-data-isnt-big-and-businesses-are-wasting-money-pretending-it-is/). This is so important and true. Big data infrastructure is often critical for creating/running data products. But discovering new ideas from data often happens on much smaller data sets with good intuition and interactive data analysis.
  5. [Really interesting article](http://www.nytimes.com/2013/05/19/sports/topps-changes-baseball-card-numbering-to-criticism.html?_r=1&) about how the baseball card numbering system matters and how changing it can upset collectors (via Chris V.).
