---
title: Exactly how risky is breathing?
author: Roger Peng
date: '2016-01-26'
output:
  distill::distill_article:
    self_contained: no
---

This [article by by George Johnson](http://nyti.ms/23nysp5) in the NYT describes a study by Kamen P. Simonov​​ and Daniel S. Himmelstein​ that examines the hypothesis that people living at higher altitudes experience lower rates of lung cancer than people living at lower altitudes.

> All of the usual caveats apply. Studies like this, which compare whole populations, can be used only to suggest possibilities to be explored in future research. But the hypothesis is not as crazy as it may sound. Oxygen is what energizes the cells of our bodies. Like any fuel, it inevitably spews out waste — a corrosive exhaust of substances called “free radicals,” or “reactive oxygen species,” that can mutate DNA and nudge a cell closer to malignancy.

I'm not so much focused on the science itself, which is perhaps intriguing, but rather on the way the article was written. First, George Johnson links to the [paper](https://peerj.com/articles/705/) itself, [already a major victory](http://simplystatistics.org/2015/01/15/how-to-find-the-science-paper-behind-a-headline-when-the-link-is-missing/). Also, I thought he did a very nice job of laying out the complexity of doing a population-level study like this one--all the potential confounders, selection bias, negative controls, etc.

I remember particulate matter air pollution epidemiology used to have this feel. You'd try to do all these different things to make the effect go away, but for some reason, under every plausible scenario, in almost every setting, there was always some association between air pollution and health outcomes. Eventually you start to believe it....
