---
title: |
  Stop saying "Scientists discover..." instead say, "Prof. Doe's team discovers..."
author: Jeff Leek
date: '2014-08-11'
output:
  distill::distill_article:
    self_contained: no
---

I was just reading an [article about data science in the WSJ](http://online.wsj.com/articles/academic-researchers-find-lucrative-work-as-big-data-scientists-1407543088). They were talking about how data scientists with just 2 years experience can earn a whole boatload of money*. I noticed a description that seemed very familiar:

> At e-commerce site operator Etsy Inc., for instance, a biostatistics Ph.D. who spent years mining medical records for early signs of breast cancer now writes statistical models to figure out the terms people use when they search Etsy for a new fashion they saw on the street.

This perfectly describes the resume of a student that worked with me here at Hopkins and is now tearing it up in industry. But it made me a little bit angry that they didn't publicize her name. Now she may have requested her name not be used, but I think it is more likely that it is a case of the standard, "Scientists discover..." (see e.g. t[his article](http://news.yahoo.com/scientists-discover-why-thrive-less-sleep-others-163712171.html) or [this one](http://www.science20.com/writer_on_the_edge/blog/scientists_discover_that_atheists_might_not_exist_and_thats_not_a_joke-139982) or [this one](http://www.huffingtonpost.com/2014/08/10/hummingbird-helicopters-technology-video_n_5659013.html?utm_hp_ref=science)).

There is always a lot of discussion about how to push people to get into STEM fields, including a ton of misguided attempts that waste time and money. But here is one way that would cost basically nothing and dramatically raise the profile of scientists in the eyes of the public: **use their names when you describe their discoveries**.

The value of this simple change could be huge. In an era of selfies, reality TV, and the power of social media, emphasizing the value that individual scientists bring could have a huge impact on STEM recruiting. That paragraph above is a lot more inspiring to potential young data scientists when rewritten:

> <span style="font-style: italic;">At e-commerce site operator Etsy Inc., for instance, Dr Hilary Parker,  a biostatistics Ph.D. who spent years mining medical records for early signs of breast cancer now writes statistical models to figure out the terms people use when they search Etsy for a new fashion they saw on the street.</span>

&nbsp;

&nbsp;

&nbsp;

&nbsp;

* _Incidentally, I think it is a bit overhyped. I have rarely heard of anyone making $200k-$300k with that little experience, but maybe I'm wrong? I'd be interested to hear if people really were making that kind of $$ at that stage in their careers. _
