---
title: Battling Bad Science
author: Admin
date: '2011-09-30'
output:
  distill::distill_article:
    self_contained: no
---

<a href="http://www.ted.com/talks/ben_goldacre_battling_bad_science.html" target="_blank">Here</a> is a pretty awesome TED talk by epidemiologist Ben Goldacre where he highlights how science can be used to deceive/mislead. It&#8217;s sort of like epidemiology 101 in 15 minutes. 

This seems like a highly topical talk. Over on his blog, Steven Salzberg has <a href="http://genome.fieldofscience.com/2011/09/dr-oz-tries-to-do-science.html" target="_blank">pointed out</a> that Dr. Oz has recently been engaging in some of these shady practices on his show. Too bad he didn&#8217;t check out the video first. 

In the comments section of the TED talk, one viewer points out that Dr. Goldacre doesn&#8217;t talk about the role of the FDA and other regulatory agencies. I think that regulatory agencies are under-appreciated and deserve credit for addressing many of these potential problems in the conduct of clinical trials. 

Maybe there should be an agency regulating how science is reported in the news? 
