---
title: The difference between data hype and data hope
author: Jeff Leek
date: '2014-06-23'
output:
  distill::distill_article:
    self_contained: no
---

I was reading one of my favorite stats blogs, [StatsChat](http://www.statschat.org.nz/), where Thomas points [to this article](http://www.theatlantic.com/technology/archive/2014/05/virtual-clinical-trials-doctors-could-use-algorithms-instead-of-people-to-test-new-drugs/371902/?mkt_tok=3RkMMJWWfF9wsRovuaTLZKXonjHpfsX86O8oW6Sg38431UFwdcjKPmjr1YIBSMFrI%2BSLDwEYGJlv6SgFSrnAMaxlzLgNXRk%3D) in the Atlantic and highlights this quote:

> Dassault Systèmes is focusing on that level of granularity now, trying to simulate propagation of cholesterol in human cells and building oncological cell models. "It's data science and modeling," Charlès told me. "Coupling the two creates a new environment in medicine."

I think that is a perfect example of data hype. This is a cool idea and if it worked would be completely revolutionary. But the reality is we are not even close to this. In very simple model organisms we can predict [very high level phenotypes some of the time](http://www.nature.com/nmeth/journal/v10/n12/full/nmeth.2724.html) with whole cell modeling. We aren't anywhere near the resolution we'd need to model the behavior of human cells, let alone the complex genetic, epigenetic, genomic, and environmental components that likely contribute to complex diseases. It is awesome that people are thinking about the future and the fastest way to science future is usually through science fiction, but this is way overstating the power of current or even currently achievable data science.

So does that mean data science for improving clinical trials right now should be abandoned?

No.

There is tons of currently applicable and real world data science being done in [sequential analysis](http://en.wikipedia.org/wiki/Sequential_analysis),  [adaptive clinical trials](http://en.wikipedia.org/wiki/Adaptive_clinical_trial), and [dynamic treatment regimes](http://en.wikipedia.org/wiki/Dynamic_treatment_regime). These are important contributions that are impacting clinical trials _right now _and where advances can reduce costs, save patient harm, and speed the implementation of clinical trials. I think that is the hope of data science - using statistics and data to make steady, realizable improvement in the way we treat patients.
