---
title: 'NIH is looking for an Associate Director for Data Science: Statisticians should
  consider applying'
author: Rafael Irizarry
date: '2013-04-08'
output:
  distill::distill_article:
    self_contained: no
---

NIH understands the importance of data and several months ago they announced this new position. Here is an excerpt from [the add](http://www.jobs.nih.gov/vacancies/executive/adds.htm):

> The ADDS will focus on the urgent need and increased opportunities for capitalizing on the expanding collections of biomedical data to advance NIH’s mission. In doing so, the incumbent will provide programmatic NIH-wide leadership for areas of data science that relate to data emanating from many areas of study (e.g., genomics, imaging, and electronic heath records). This will require knowledge about multiple domains of study as well as familiarity with approaches for integrating data from these various domains.

In my opinion, the person holding this job should have hands-on experience with data analysis and programming. The <del>nuisances</del> nuances of what a data analyst needs to successfully do his/her job can't be underestimated. This knowledge will help this director make the right decisions when it comes to choosing what data to make available and how to make it available.  When it comes to creating data resources, good intentions don't always translate into usable products.

In this new era of data driven science this position will be highly influential making this job quite attractive. If you know of a Statistician that you think is interested please pass along the information.
