---
title: Out with Big Data, in with Hyperdata
author: Roger Peng
date: '2013-11-11'
output:
  distill::distill_article:
    self_contained: no
---

Big data is so [last year](http://www.nytimes.com/2013/11/11/technology/gathering-more-data-faster-to-produce-more-up-to-date-information.html).

> <p itemprop="articleBody">
>   Collecting data from all sorts of odd places and analyzing it much faster than was possible even a couple of years ago has become one of the hottest areas of the technology industry. The idea is simple: With all that processing power and a little creativity, researchers should be able to find novel patterns and relationships among different kinds of information.
> </p>
> 
> <p itemprop="articleBody">
>   For the last few years, insiders have been calling this sort of analysis Big Data. Now Big Data is evolving, becoming more “hyper” and including all sorts of sources. Start-ups like Premise and ClearStory Data, as well as larger companies like General Electric, are getting into the act.
> </p>
> 
> <p itemprop="articleBody">
>   ...
> </p>
> 
> <p itemprop="articleBody">
>   “Hyperdata comes to you on the spot, and you can analyze it and act on it on the spot,” said Bernt Wahl, an industry fellow at the Center for Entrepreneurship and Technology at the University of California, Berkeley. “It will be in regular business soon, with everyone predicting and acting the way Amazon instantaneously changes its prices around.”
> </p>
