---
title: Let's make the Joint Statistical Mettings modular
author: Admin
date: '2012-10-23'
output:
  distill::distill_article:
    self_contained: no
---

Have you ever met a statistician that enjoys the joint statistical meetings (JSM)? I haven&#8217;t. With the exception of the one night we catch up with old friends there are few positive things we can say about JSM.They are way too big and the two talks I want to see are always somehow scheduled at the same time as mine.

But statisticians actually like conferences. Most of us have a favorite statistics conference, or session within a bigger subject matter conference, that we look forward to going to. But it&#8217;s never JSM. So why can&#8217;t JSM just be a collection of these conferences? For sure we should drop the current format and come up with something new.

I propose that we start by giving each ASA section two non-concurrent sessions scheduled on two consecutive days (perhaps more slots for bigger sections) and let them do whatever they want. Hopefully they would turn this into the conference that they want to go to. It&#8217;s our meeting, we pay for it, so let&#8217;s turn it into something we like.
