---
title: Cooperation between Referees and Authors Increases Peer Review Accuracy
author: Admin
date: '2011-11-11'
output:
  distill::distill_article:
    self_contained: no
---

Jeff Leek and colleagues just published an article in PLoS ONE on the <a href="http://www.plosone.org/article/info:doi%2F10.1371%2Fjournal.pone.0026895" target="_blank">differences between anonymous (closed) and non-anonymous (open) peer review of research articles</a>. They developed a &#8220;peer review game&#8221; as a model system to track authors&#8217; and reviewers&#8217; behavior over time under open and closed systems.

Under the open system, it was possible for authors to see who was reviewing their work. They found that under the open system authors and reviewers tended to cooperate by reviewing each others&#8217; work. Interestingly, they say

> <span>It was not immediately clear that cooperation between referees and authors would increase reviewing accuracy. Intuitively, one might expect that players who cooperate would always accept each others solutions - regardless of whether they were correct. However, we observed that when a submitter and reviewer acted cooperatively, reviewing accuracy actually increased by 11%.</span>
