---
title: Caffo + Ninjas = Awesome
author: Admin
date: '2011-10-18'
output:
  distill::distill_article:
    self_contained: no
---

Our colleague <a href="http://www.biostat.jhsph.edu/~bcaffo/" target="_blank">Brian Caffo</a> and his team of statistics ninjas won the &#8220;Imaging-Based Diagnostic Classification Contest&#8221; as part of the <a href="http://fcon_1000.projects.nitrc.org/indi/adhd200/results.html" target="_blank">ADHD 200 Global Competition</a>. From the prize citation:

> <span>The method developed by the team from Johns Hopkins University excelled in its <strong>specificity</strong>, or its ability to identify typically developing children (TDC) without falsely classifying them as ADHD-positive. They correctly classified 94% of TDC, showing that a diagnostic imaging methodology can be developed with a very low risk of false positives, a fantastic result. Their method was not as effective in terms of <strong>sensitivity</strong>, or its ability to identify true positive ADHD diagnoses. They only identified 21% of cases; however, among those cases, they discerned the subtypes of ADHD with 89.47% accuracy. Other teams demonstrated that there is ample room to improve sensitivity scores. </span>

<span>Congratulations to Brian and his team!</span>
