---
title: When dealing with poop, it's best to just get your hands dirty
author: Admin
date: '2012-08-11'
output:
  distill::distill_article:
    self_contained: no
---

I&#8217;m a relatively new dad. Before the kid we affectionately call the &#8220;tiny tornado&#8221; (TT) came into my life, I had relatively little experience dealing with babies and all the fluids they emit. So admittedly, I was a little squeamish dealing with the poopy explosions the TT would create. Inevitably, things would get much more messy than they had to be while I was being too delicate with the issue. It took me an embarrassingly long time for an educated man, but I finally realized you just have to get in there and change the thing even if it is messy, then wash your hands after. It comes off. 

It is a similar situation in my professional life, but I&#8217;m having a harder time learning the lesson. There are frequently things that I&#8217;m not really excited to do: review a lot of papers, go to long meetings, revise a draft of that paper that has just been sitting around forever. Inevitably, once I get going they usually aren&#8217;t as difficult or as arduous as I thought. Even better, once they are done I feel a huge sense of accomplishment and relief. I used to have a metaphor for this, I&#8217;d tell myself, &#8220;Jeff, just rip off the band-aid&#8221;. Now, I think &#8220;Jeff, just get your hands dirty&#8221;. 
