---
title: Sunday data/statistics link roundup (1/13/2013)
author: Jeff Leek
date: '2013-01-13'
output:
  distill::distill_article:
    self_contained: no
---

  1. [These](http://www.seaborg.ucla.edu/video2012.html) are some great talks. But definitely watch Michael Eisen's talk on E-biomed and the history of open access publication. This is particularly poigniant in light of [Aaron Swartz's tragic suicide](http://www.nytimes.com/2013/01/13/technology/aaron-swartz-internet-activist-dies-at-26.html?_r=0). It's also worth checking out the twitter hashtag [#pdftribute ](https://twitter.com/search?q=%23pdftribute&src=hash).
  2. An [awesome flowchart](http://civilstat.com/wp-content/uploads/2013/01/IMG_8807-1024x768.jpg) before a talk given by the creator of the R [twotuorials](http://www.twotorials.com/). Roger gets a shoutout (via civilstat).
  3. [This blog](http://stochasticplanet.tumblr.com/) selects a position at random on the planet earth every day and posts the picture taken closest to that point. Not much about the methodology on the blog, but totally fascinating and a clever idea.
  4. A set of data giving a ["report card"](http://reportcard.studentsfirst.org/) for each state on how that state does in improving public education for students. I'm not sure I believe the grades, but the underlying reports look interesting.
