---
title: The more statistics blogs the better
author: Admin
date: '2012-10-02'
output:
  distill::distill_article:
    self_contained: no
---

Good friend and friend of the blog Rob Gould has started a statistics blog called <a href="http://citizen-statistician.org" target="_blank">Citizen Statistician</a>. What is a citizen statistician, you ask?

> <span>What is a citizen statistician? A citizen statistician participates in formal and informal data gathering. A citizen statistician is aware of his or her data trail, and is aware of the harm that could be done to themselves or to others through data aggregation. Citizen statisticians recognize opportunities to improve their personal or professional lives through analyzing data, and know how to share data with others. They know that almost any question about the world can be answered using data, how to find relevant data sources on the web, and critically evaluate these sources. A citizen statistician also knows how to bring that data into an analysis package and how to start their investigation.</span>

What&#8217;s even better than having more statistics blogs? Having more statisticians.
