---
title: The Leek group guide to sharing data with a data analyst to speed collaboration
author: Jeff Leek
date: '2013-11-14'
output:
  distill::distill_article:
    self_contained: no
---

My group collaborates with many different scientists and the number one determinant of how fast we can turn around results is the status of the data we receive from our collaborators. If the data are well organized and all the important documentation is there, it dramatically speeds up the analysis time.

I recently had the experience where a postdoc requesting help with an analysis provided an amazing summary of the data she wanted analyzed. It has made me want to prioritize her analysis in my queue and it inspired me to write a how-to guide that will help scientific/business collaborators get speedier results from their statistician colleagues.

Here is the [Leek group guide to sharing data with statisticians/data analysts](https://github.com/jtleek/datasharing).

As usual I put it on Github because I'm sure this first draft will have mistakes or less than perfect ideas. I would love help in making the guide more comprehensive and useful. If you issue a pull request make sure you add yourself to list of contributors at the end.
