---
title: Sunday data/statistics link roundup (12/7/14)
author: Jeff Leek
date: '2014-12-07'
output:
  distill::distill_article:
    self_contained: no
---

  1. [A randomized controlled trial](http://www.apa.org/news/press/releases/2014/11/airport-security.aspx) shows that using conversation to detect suspicious behavior is much more effective then just monitoring body language (via Ann L. on Twitter). This comes as a crushing blow to those of us who enjoyed the now-cancelled [Lie to Me](http://en.wikipedia.org/wiki/Lie_to_Me) and assumed it was all real.
  2. Check out this awesome [real-time visualization](http://map.ipviking.com/) of different types of network attacks. Rafa says if you watch long enough you will almost certainly observe a "storm" of attacks. A cool student project would be modeling the distribution of these attacks if you could collect the data (via David S.).
  3. [Consider this: Did Big Data Kill the Statistician?](http://goodstrat.com/2014/12/03/consider-this-did-big-data-kill-the-statistician/) I understand the sentiment, that statistical thinking and applied statistics has been around a long time and has [produced some good ideas](http://simplystatistics.org/2014/05/22/10-things-statistics-taught-us-about-big-data-analysis/). On the other hand, there is definitely a large group of statisticians who aren't willing to expand their thinking beyond a really narrow set of ideas (via Rafa)
  4. [Gangnam Style viewership creates integers too big for Youtube](http://www.huffingtonpost.com/2014/12/03/gangnam-style-youtube_n_6261332.html) (via Rafa)
  5. A couple of interviews worth reading, [  1. [A randomized controlled trial](http://www.apa.org/news/press/releases/2014/11/airport-security.aspx) shows that using conversation to detect suspicious behavior is much more effective then just monitoring body language (via Ann L. on Twitter). This comes as a crushing blow to those of us who enjoyed the now-cancelled [Lie to Me](http://en.wikipedia.org/wiki/Lie_to_Me) and assumed it was all real.
  2. Check out this awesome [real-time visualization](http://map.ipviking.com/) of different types of network attacks. Rafa says if you watch long enough you will almost certainly observe a "storm" of attacks. A cool student project would be modeling the distribution of these attacks if you could collect the data (via David S.).
  3. [Consider this: Did Big Data Kill the Statistician?](http://goodstrat.com/2014/12/03/consider-this-did-big-data-kill-the-statistician/) I understand the sentiment, that statistical thinking and applied statistics has been around a long time and has [produced some good ideas](http://simplystatistics.org/2014/05/22/10-things-statistics-taught-us-about-big-data-analysis/). On the other hand, there is definitely a large group of statisticians who aren't willing to expand their thinking beyond a really narrow set of ideas (via Rafa)
  4. [Gangnam Style viewership creates integers too big for Youtube](http://www.huffingtonpost.com/2014/12/03/gangnam-style-youtube_n_6261332.html) (via Rafa)
  5. A couple of interviews worth reading,](http://simplystatistics.org/2014/12/05/interview-with-cole-trapnell-of-uw-genome-sciences/) and [SAMSI's with Jyotishka Data](http://samsiatrtp.wordpress.com/2014/11/18/samsi-postdoctoral-profile-jyotishka-datta/) (via Jamie N.)
  6.  [A piece on the secrets we don't know we are giving away](http://www.theguardian.com/technology/2014/dec/05/when-data-gets-creepy-secrets-were-giving-away) through giving our data to [companies/the government/the internet].
