---
title: Discussion of the Theranos Controversy with Elizabeth Matsui
author: Roger Peng
date: '2015-10-28'
output:
  distill::distill_article:
    self_contained: no
---

Theranos is a Silicon Valley diagnostic testing company that has been in the news recently. The story of Theranos has fascinated me because I think it represents a perfect collision of the tech startup culture and the health care culture and how combining them together can generate unique problems.

I talked with Elizabeth Matsui, a Professor of Pediatrics in the Division of Allergy and Immunology here at Johns Hopkins, to discuss Theranos, the realities of diagnostic testing, and the unique challenges that a health-tech startup faces with respect to doing good science and building products people want to buy.



Notes:

  * Original [Wall Street Journal story](http://www.wsj.com/articles/theranos-has-struggled-with-blood-tests-1444881901) on Theranos (paywalled)
  * Related stories in [Wired](http://www.wired.com/2015/10/theranos-scandal-exposes-the-problem-with-techs-hype-cycle/) and NYT's [Dealbook](http://www.nytimes.com/2015/10/28/business/dealbook/theranos-under-fire.html) (not paywalled)
  * Theranos [response](https://www.theranos.com/news/posts/custom/theranos-facts) to WSJ story


<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/230510705%3Fsecret_token%3Ds-WbZX8&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>


