---
title: figshare and don't trust celebrities stating facts
author: Admin
date: '2012-01-17'
output:
  distill::distill_article:
    self_contained: no
---

A couple of links:

  1. <a href="http://figshare.com/" target="_blank">figshare</a> is a site where scientists can share data sets/figures/code. One of the goals is to encourage researchers to share negative results as well. I think this is a great idea - I often find negative results and this could be a place to put them. It also uses a tagging system, like Flickr. I think this is a great idea for scientific research discovery. They give you unlimited public space and 1GB of private space. This could be big, a place to help make <a href="http://simplystatistics.tumblr.com/post/13633695297/reproducible-research-in-computational-science" target="_blank">reproducible research efforts</a> user-friendly. Via <a href="http://techcrunch.com/2012/01/17/science-data-sharing-site-figshare-relaunches-adds-features/" target="_blank">TechCrunch</a>
  2. Don&#8217;t trust <a href="http://newsfeed.time.com/2012/01/03/celebrities-offering-scientific-facts-just-say-no/?xid=newsletter-weekly" target="_blank">celebrities stating facts</a> because they usually don&#8217;t know what they are talking about. I completely agree with this. Particularly because I have serious doubts about the <a href="http://simplystatistics.tumblr.com/post/15774146480/in-the-era-of-data-what-is-a-fact" target="_blank">statisteracy</a> of most celebrities. Nod to Alex for the link (our most active link finder!).  
