---
title: Sunday data/statistics link roundup (3/24/2013)
author: Jeff Leek
date: '2013-03-24'
output:
  distill::distill_article:
    self_contained: no
---

  1. <span style="font-size: 16px">My Coursera Data Analysis class is done for now! All the lecture notes </span><a style="font-size: 16px" href="https://github.com/jtleek/dataanalysis">are on Github</a><span style="font-size: 16px"> all the videos </span><a style="font-size: 16px" href="http://www.youtube.com/user/jtleek2007/videos?sort=dd&tag_id=UC8xNPQ-3a5t9uMU7Vah-jWA.3.coursera&view=46">are on Youtube</a><span style="font-size: 16px">. They are tagged by week with tags "Week x".</span>
  2. After ENAR the comments on how to have better stats conferences started flowing. Check out [Frazee](http://alyssafrazee.wordpress.com/2013/03/18/ideas-for-super-awesome-conferences/), [Xie](http://yihui.name/en/2013/03/on-enar-or-statistical-meetings-in-general/), and [Broman](http://kbroman.wordpress.com/2013/03/19/enar-highs-and-lows/). My favorite cherry picked ideas: conference app (frazee), giving the poster session more focus (frazee), free and announced wifi (broman), more social media (i loved following ENAR [on twitter](https://twitter.com/search/realtime?q=%23ENAR2013&src=hash) but wish there had been more tweeting) (xie), add some jokes to talks (xie).
  3. A related post is this one from Hilary M. on how a talk s[hould entertain, not teach](http://www.hilarymason.com/speaking/speaking-entertain-dont-teach/).
  4. This is a [  1. <span style="font-size: 16px">My Coursera Data Analysis class is done for now! All the lecture notes </span><a style="font-size: 16px" href="https://github.com/jtleek/dataanalysis">are on Github</a><span style="font-size: 16px"> all the videos </span><a style="font-size: 16px" href="http://www.youtube.com/user/jtleek2007/videos?sort=dd&tag_id=UC8xNPQ-3a5t9uMU7Vah-jWA.3.coursera&view=46">are on Youtube</a><span style="font-size: 16px">. They are tagged by week with tags "Week x".</span>
  2. After ENAR the comments on how to have better stats conferences started flowing. Check out [Frazee](http://alyssafrazee.wordpress.com/2013/03/18/ideas-for-super-awesome-conferences/), [Xie](http://yihui.name/en/2013/03/on-enar-or-statistical-meetings-in-general/), and [Broman](http://kbroman.wordpress.com/2013/03/19/enar-highs-and-lows/). My favorite cherry picked ideas: conference app (frazee), giving the poster session more focus (frazee), free and announced wifi (broman), more social media (i loved following ENAR [on twitter](https://twitter.com/search/realtime?q=%23ENAR2013&src=hash) but wish there had been more tweeting) (xie), add some jokes to talks (xie).
  3. A related post is this one from Hilary M. on how a talk s[hould entertain, not teach](http://www.hilarymason.com/speaking/speaking-entertain-dont-teach/).
  4. This is a](http://blogs.spectator.co.uk/books/2013/03/interview-with-a-writer-jaron-lanier/) I found via AL Daily. My favorite lines? "You run into this attitude, that if ordinary people cannot set their Facebook privacy settings, then they deserve what is coming to them. There is a hacker superiority complex to this." I think this is certainly something we have a lot of in statistics as well.
  5. The CIA wants to [collect all the dataz](http://www.rawstory.com/rs/2013/03/21/cias-big-data-mission-collect-everything-and-hang-onto-it-forever/). Call me when cat videos become important for national security, ok guys?
  6. Given I just completed my class, the [MOOC completion rates](http://www.katyjordan.com/MOOCproject.html) graph is pretty appropriate. I think my #'s are right in line with that other people report. I'm still trying to figure out how to know how many people "completed" the class.
