---
title: Statistics takes center stage in the Independent
author: Jeff Leek
date: '2013-07-26'
output:
  distill::distill_article:
    self_contained: no
---

Check out [this really good piece](http://www.independent.co.uk/news/world/americas/heroes-of-zeroes-nate-silver-his-rivals-and-the-big-electoral-data-revolution-8734380.html) over at the Independent. It talks about the rise of statisticians as rockstars, naming Hans Rosling, Nate Silver, and Chris Volinsky among others. I think that those guys are great and deserve all the attention they get.

I only hope that more of the superstars that fly under the radar of the general public but have made huge contributions  to science/medicine (like Ross Prentice, Terry Speed, Scott Zeger, or others that were highlighted in the comments [here](http://simplystatistics.org/2013/07/17/name-5-statisticians-now-name-5-young-statisticians/)) get the same kind of attention (although I suspect they might not want it).

I think one of the best parts of the article (which you should read in it's entirety) is Marie Davidian's quote:

> There are rock stars, and then there are rock bands: statisticians frequently work in teams
