---
title: Sunday data/statistics link roundup (10/27/13)
author: Jeff Leek
date: '2013-10-27'
output:
  distill::distill_article:
    self_contained: no
---

  1. [Pubmed Commons](http://www.ncbi.nlm.nih.gov/pubmedcommons/) is a new post-publication commenting system. I think this is a great idea and I hope it succeeds. Right now it is in "private beta" so only people with Pubmed Commons accounts can post/view comments. But you can follow along with who is making comments via [this neat twitter bot](https://twitter.com/pmctrawler). I think the main feature this lacks to be a hugely successful experiment is some way to give real, tangible academic credit to commenters. One very obvious way would be by assigning DOIs to every comment and making the comments themselves Pubmed searchable. Then they could be listed as contributions on CVs - a major incentive.
  2. [A post](http://countaleph.wordpress.com/2013/10/20/dear-startups-stop-asking-me-math-puzzles-to-figure-out-if-i-can-code/) on the practice of asking potential hires tricky math problems  - even if they are going to be hired to do something else (like software engineering). This happens all the time in academia as well - often the exams we give/questions we ask aren't neatly aligned with the ultimate goals of a program (producing innovative/determined researchers).
  3. This is going to be a short Sunday Links because my [Coursera class](https://www.coursera.org/course/dataanalysis) is starting again tomorrow.
  4. Don't forget that next week is the [  1. [Pubmed Commons](http://www.ncbi.nlm.nih.gov/pubmedcommons/) is a new post-publication commenting system. I think this is a great idea and I hope it succeeds. Right now it is in "private beta" so only people with Pubmed Commons accounts can post/view comments. But you can follow along with who is making comments via [this neat twitter bot](https://twitter.com/pmctrawler). I think the main feature this lacks to be a hugely successful experiment is some way to give real, tangible academic credit to commenters. One very obvious way would be by assigning DOIs to every comment and making the comments themselves Pubmed searchable. Then they could be listed as contributions on CVs - a major incentive.
  2. [A post](http://countaleph.wordpress.com/2013/10/20/dear-startups-stop-asking-me-math-puzzles-to-figure-out-if-i-can-code/) on the practice of asking potential hires tricky math problems  - even if they are going to be hired to do something else (like software engineering). This happens all the time in academia as well - often the exams we give/questions we ask aren't neatly aligned with the ultimate goals of a program (producing innovative/determined researchers).
  3. This is going to be a short Sunday Links because my [Coursera class](https://www.coursera.org/course/dataanalysis) is starting again tomorrow.
  4. Don't forget that next week is the](https://plus.google.com/events/cd94ktf46i1hbi4mbqbbvvga358) on Wednesday, October 30th at noon Baltimore time!
