---
title: Sunday data/statistics link roundup (6/23/13)
author: Jeff Leek
date: '2013-06-23'
output:
  distill::distill_article:
    self_contained: no
---

  1. [An interesting study](http://www.plosone.org/article/info:doi%2F10.1371%2Fjournal.pone.0066463) describing the potential benefits of using significance testing may be potentially beneficial and a scenario where the file drawer effect may even be beneficial. Granted this is all simulation so you have to take it with a grain of salt, but I like the pushback against the hypothesis testing haters. In all things moderation, including hypothesis testing.
  2. [Venn Diagrams for the win, bro](http://www.npr.org/blogs/codeswitch/2013/06/21/193881290/jeah-we-mapped-out-the-four-basic-aspects-of-being-a-bro).
  3. [The new basketball positions](http://www.youtube.com/watch?v=E-gpSQQe3w8). The idea is to cluster players based on the positions on the floor where they shoot, etc. I like the idea of data driven position definitions; I am a little worried about "reading ideas in" to a network picture.
  4. [A really cool idea](http://qz.com/95516/an-start-ups-plan-to-make-us-health-care-cheaper-tell-people-what-it-costs/) about a startup that makes data on healthcare procedures available to patients. I'm all about data transparency, but it makes me wonder, how often do people with health insurance negotiate the prices of procedures (via Leah J.)
  5. Another interesting article [about using tweets](http://www.nytimes.com/2013/06/23/opinion/sunday/theres-a-fly-in-my-tweets.html?emc=eta1&_r=0) (and other social media) to improve public health. I do wonder about potential sampling issues, like what happened with [google flu trends](http://bits.blogs.nytimes.com/2013/02/24/disruptions-google-flu-trends-shows-problems-of-big-data-without-context/) (via Nick C.)
