---
title: Data Analysis for Genomics edX Course
author: Rafael Irizarry
date: '2014-03-31'
output:
  distill::distill_article:
    self_contained: no
---

Mike Love (@mikelove) and I have been working hard the past couple of months preparing a free online [edX](https://www.edx.org/) course on [data analysis for genomics](https://www.edx.org/course/harvardx/harvardx-ph525x-data-analysis-genomics-1401). Our target audience are the postdocs, graduate students and research scientists that are tasked with analyzing genomics data, but don't have any formal training. The eight week course will start with the very basics, but will ramp up rather quickly and end with real-life workflows for genome variation, RNA-seq, DNA methylation, and ChIP-seq.

Throughout the course students will learn skills and concepts that provide a foundation for analyzing genomics data. Specifically, we will cover exploratory data analysis, basic statistical inference, linear regression, modeling with parametric distributions, empirical Bayes, multiple comparison corrections and smoothing techniques.

In the class we will make heavy use of computer labs. Almost every lecture is accompanied by an R markdown document that students can use to recreate the plots shown in the lectures. The html document resulting from these R markdown files will result in an html document that will serve as a text book for the class.

Questions will be discussed on online forums led by Stephanie Hicks (@stephaniehicks) and Jim MacDonald.

If you want to sign up, [here](https://www.edx.org/course/harvardx/harvardx-ph525x-data-analysis-genomics-1401) is the link.
