---
title: The Leek group guide to writing your first paper
author: Jeff Leek
date: '2015-09-18'
output:
  distill::distill_article:
    self_contained: no
---

<blockquote class="twitter-tweet" width="550">
  <p lang="en" dir="ltr">
    The <a href="https://twitter.com/jtleek">@jtleek</a> guide to writing your first academic paper <a href="https://t.co/APLrEXAS46">https://t.co/APLrEXAS46</a>
  </p>
  
  <p>
    &mdash; Stephen Turner (@genetics_blog) <a href="https://twitter.com/genetics_blog/status/644540432534368256">September 17, 2015</a>
  </p>
</blockquote>



I have written guides on [reviewing papers](https://github.com/jtleek/reviews), [sharing data](https://github.com/jtleek/datasharing),  and [writing R packages](https://github.com/jtleek/rpackages). One thing I haven't touched on until now has been writing papers. Certainly for me, and I think for a lot of students, the hardest transition in graduate school is between taking classes and doing research.

There are several hard parts to this transition including trying to find a problem, trying to find an advisor, and having a ton of unstructured time. One of the hardest things I've found is knowing (a) when to start writing your first paper and (b) how to do it. So I wrote a guide for students in my group:

<https://github.com/jtleek/firstpaper>

On how to write your first paper. It might be useful for other folks as well so I put it up on Github. Just like with the other guides I've written this is a very opinionated (read: doesn't apply to everyone) guide. I also would appreciate any feedback/pull requests people have.
