---
title: Introduction to Linear Models and Matrix Algebra MOOC starts this Monday Feb
  16
author: Rafael Irizarry
date: '2015-02-13'
output:
  distill::distill_article:
    self_contained: no
---

Matrix algebra is the language of modern data analysis. We use it to develop and describe statistical and machine learning methods, and to code efficiently in languages such as R, matlab and python. Concepts such as principal component analysis (PCA) are best described with matrix algebra. It is particularly useful to describe linear models.

Linear models are everywhere in data analysis. ANOVA, linear regression, limma, edgeR, DEseq, most smoothing techniques, and batch correction methods such as SVA and Combat are based on linear models. In this two week MOOC we well describe the basics of matrix algebra, demonstrate how linear models are used in the life sciences and show how to implement these efficiently in R.

Update: Here is [the link](https://www.edx.org/course/introduction-linear-models-matrix-harvardx-ph525-2x) to the class
