---
title: Proof by example and letters of recommendation
author: Admin
date: '2012-07-24'
output:
  distill::distill_article:
    self_contained: no
---

In math or statistics, proof by example does not work. One example of a phenomenon does not prove anything. For example, because 2 is prime doesn&#8217;t mean that all even numbers are prime. In fact, no even numbers other than 2 are prime. 

But in other areas proof by example is the best way to demonstrate something. One example is writing letters of recommendation. It is way more convincing when I get one example of something a person has achieved:

> Kyle created the first R package that can be used to analyze terabytes of sequencing data in under an hour.

Than something much more general but with no details:

> Bryan is an excellent programmer with a mastery of six different programming languages. 

In mathematics it makes sense why proof by example does not work. There is a concrete result and even one example violating that result means it isn&#8217;t true. On the other hand, if most of the time Kyle crushes his work, but every once in a while he has an off day and doesn&#8217;t get it done, I can live with that. That&#8217;s true of a lot of applied statistical methods too. If it works 99% of the time and 1% of the time fails but you can discover how it failed, that is still a pretty good statistical method&#8230;
