---
title: Statistical Crime Fighter
author: Admin
date: '2012-01-10'
output:
  distill::distill_article:
    self_contained: no
---

<a href="http://www-stat.wharton.upenn.edu/~berkr/" target="_blank">Dick Berk</a> is using his statistical superpowers to fight crime. <a href="http://www.theatlantic.com/magazine/archive/2012/01/misfortune-teller/8846/" target="_blank">Seriously</a>. Here is my favorite paragraph.

> <span>Drawing from criminal databases dating to the 1960s, Berk initially modeled the Philadelphia algorithm on more than 100,000 old cases, relying on three dozen predictors, including the perpetrator’s age, gender, neighborhood, and number of prior crimes. To develop an algorithm that forecasts a particular outcome—someone committing murder, for example—Berk applied a subset of the data to “train” the computer on which qualities are associated with that outcome. “If I could use sun spots or shoe size or the size of the wristband on their wrist, I would,” Berk said. “If I give the algorithm enough predictors to get it started, it finds things that you wouldn’t anticipate.” Philadelphia’s parole officers were surprised to learn, for example, that the crime for which an offender was sentenced—whether it was murder or simple drug possession—does not predict whether he or she will commit a violent crime in the future. Far more predictive is the age at which he (yes, gender matters) committed his first crime, and the amount of time between other offenses and the latest one—the earlier the first crime and the more recent the last, the greater the chance for another offense.</span>

<span>Hat tip to Alex Nones.</span>
