---
title: Interview at Leanpub
author: Roger Peng
date: '2015-06-16'
output:
  distill::distill_article:
    self_contained: no
---

A few weeks ago I sat down with Len Epp over at Leanpub to talk about my recently published book _[R Programming for Data Science](https://leanpub.com/rprogramming)_. So far, I've only published one book through Leanpub but I'm a huge fan. They've developed a system that is, in my opinion, perfect for academic publishing. The book's written in Markdown and they compile it into PDF, ePub, and mobi formats automatically.

The full interview transcript is over at the [Leanpub blog](http://blog.leanpub.com/2015/06/roger-peng.html). If you want to listen to the audio of the interview, you can subscribe to the Leanpub [podcast on iTunes](https://itunes.apple.com/ca/podcast/id517117137?mt=2).

[_R Programming for Data Science_](https://leanpub.com/rprogramming) is available at Leanpub for a suggested price of $15 (but you can get it for free if you want). R code files, datasets, and video lectures are available through the various add-on packages. Thanks to all of you who've already bought a copy!
