---
title: Teaser trailer for the Genomic Data Science Specialization on Coursera
author: Jeff Leek
date: '2015-03-26'
output:
  distill::distill_article:
    self_contained: no
---

&nbsp;

We have been hard at work in the studio putting together our next specialization to launch on Coursera. It will be called the "Genomic Data Science Specialization" and includes a spectacular line up of instructors: [Steven Salzberg](http://salzberg-lab.org/), [Ela Pertea](http://ccb.jhu.edu/people/mpertea/), [James Taylor](http://jamestaylor.org/), [Liliana Florea](http://ccb.jhu.edu/people/florea/), [Kasper Hansen](http://www.hansenlab.org/), and me. The specialization will cover command line tools, statistics, Galaxy, Bioconductor, and Python. There will be a capstone course at the end of the sequence featuring an in-depth genomic analysis. If you are a grad student, postdoc, or principal investigator in a group that does genomics this specialization is for you. If you are a person looking to transition into one of the hottest areas of research with the new precision medicine initiative this is for you. Get pumped and share the teaser-trailer with your friends!
