---
title: 2-D author lists
author: Admin
date: '2012-10-03'
output:
  distill::distill_article:
    self_contained: no
---

The order of authors on scientific papers matters a lot. The best places to be on a paper <a href="http://simplystatistics.org/post/11314293165/authorship-conventions" target="_blank">vary by field</a>. But typically the first and the corresponding (usually last) authors are the prime real estate. When people are evaluated on the job market, for promotion, or to get grants, the number of first/corresponding author papers can be the difference between success and failure. 

At the same time, many journals list &#8220;authors contributions&#8221; at the end of the manuscript, but this is rarely prominently displayed. The result is that regardless of the true distribution of credit in a manuscript, the first and last authors get the bulk of the benefit. 

This system is antiquated for a few reasons:

  1. In multidisciplinary science, there are often equal and very different contributions from people working in different disciplines. 
  2. Science is increasing collaborative, even within a single discipline and papers are rarely the effort of 2 people anymore. 

How about a 2-D, resortable author list? Each author is a column and each kind of contribution is a row. The contributions are: (1) conceived the idea, (2) collected the data, (3) did the computational analysis, (4) wrote the paper (you could imagine adding others). Each category then gets a quantitative number, fraction of the effort to that component of the paper. Then you build an interactive graphic that allows you to sort the authors by each of the categories. So you could see who did what on the paper. 

To get an overall impression of which activities an author performs, you could average their contribution across papers in each of the categories. Creating a &#8220;heatmap of contributions&#8221;. Anyone want to build this? 
