---
title: Sunday data/statistics link roundup (10/13/13)
author: Jeff Leek
date: '2013-10-13'
output:
  distill::distill_article:
    self_contained: no
---

  1. A really interesting comparison [between educational and TV menus](http://marginalrevolution.com/marginalrevolution/2013/10/online-education-and-the-tivo-revolution.html) (via Rafa). On a related note, it will be interesting to see [how/whether the traditional educational system will be disrupted](http://www.slate.com/articles/technology/education/2013/09/edx_mit_and_online_certificates_how_non_degree_certificates_are_disrupting.html). I'm as into the MOOC thing as the next guy, but I'm not sure I buy a series of pictures from your computer as "validation" you took/know the material for a course. Also I'm not 100% sure about what this is, but it has the potential to be kind of awesome - [the Moocdemic](https://www.moocdemic.com/).
  2. [This piece](http://www.sciencemag.org/content/342/6154/60.full) of "investigative journalism" had the open-access internet up in arms. The piece shows pretty clearly that there are bottom-feeding journals who will use unscrupulous tactics and claim peer review while doing no such thing. But it says basically nothing about open access as far as I can tell. On a related note, a couple of years ago we [developed an economic model for peer review](http://www.plosone.org/article/info:doi/10.1371/journal.pone.0026895), then tested the model out. In a very contrived/controlled system we showed peer review improves accuracy, even when people aren't incentivized to review.
  3. Related to [our guest post](http://simplystatistics.org/2013/10/10/cancelled-nih-study-sections-a-subtle-yet-disastrous-effect-of-the-government-shutdown/) on NIH study sections is this [pretty depressing piece in Nature](http://www.nature.com/news/nih-campus-endures-slow-decay-1.13942).
  4. One of JHU Biostat's NSF graduate research fellows [was interviewed by Amstat News](http://stattrak.amstat.org/2013/10/01/fellowship-experience/).
  5. Jenny B. has [some great EDA lectures](http://www.stat.ubc.ca/~jenny/STAT545A/2012-lectures/) you should check out.
