---
title: Statisticians on Twitter...help me find more!
author: Admin
date: '2011-11-09'
output:
  distill::distill_article:
    self_contained: no
---

In honor of our blog finally dragging itself into the 21st century and jumping onto Twitter/Facebook, I have been compiling a list of statistical people on Twitter. I couldn&#8217;t figure out an easy way to find statisticians in one go (which could be because I don&#8217;t have Twitter skills). 

So here is my very informal list of statisticians I found in a half hour of searching. I know I missed a ton of people; let me know who I missed so I can update!

<a href="http://twitter.com/#!/leekgroup" target="_blank">@leekgroup</a> - Jeff Leek (What, you thought I&#8217;d list someone else first?)

<a href="http://twitter.com/#!/rdpeng" target="_blank">@rdpeng</a> - Roger Peng

<a href="http://twitter.com/#!/rafalab" target="_blank">@rafalab</a> - Rafael Irizarry

<a href="http://twitter.com/#!/storeylab" target="_blank">@storeylab</a> - John Storey

<a href="http://twitter.com/#!/bcaffo" target="_blank">@bcaffo</a> - Brian Caffo

<a href="http://twitter.com/#!/sherrirose" target="_blank">@sherrirose </a>- Sherri Rose

<a href="http://twitter.com/#!/raphg" target="_blank">@raphg </a>- Raphael Gottardo

<a href="http://twitter.com/#!/airoldilab" target="_blank">@airoldilab</a> - Edo Airoldi

<a href="http://twitter.com/#!/stat110" target="_blank">@stat110</a> - Joe Blitzstein

<a href="http://twitter.com/#!/tylermccormick" target="_blank">@tylermccormick</a> - Tyler McCormick

<a href="http://twitter.com/#!/statpumpkin" target="_blank">@statpumpkin</a> - Chris Volinsky

<a href="http://twitter.com/#!/fivethirtyeight" target="_blank">@fivethirtyeight</a> - Nate Silver

<a href="http://twitter.com/#!/flowingdata" target="_blank">@flowingdata</a> - Nathan Yau

<a href="http://twitter.com/#!/kinggary" target="_blank">@kinggary</a> - Gary King

<a href="http://twitter.com/#!/StatModeling" target="_blank">@StatModeling</a> - Andrew Gelman

<a href="http://twitter.com/#!/AmstatNews" target="_blank">@AmstatNews</a> - Amstat News

<a href="http://twitter.com/#!/hadleywickham" target="_blank">@hadleywickham</a> - Hadley Wickham
