---
title: Return of the sunday links! (10/26/14)
author: Jeff Leek
date: '2014-10-26'
output:
  distill::distill_article:
    self_contained: no
---

New look for the blog and bringing back the links. If you have something that you'd like included in the Sunday links, email me and let me know. If you use the title of the message "Sunday Links" you'll be more likely for me to find it when I search my gmail.

  1. Thomas L. does a more technical post on [semi-parametric efficiency](http://notstatschat.tumblr.com/post/100893932596/semiparametric-efficiency-and-nearly-true-models), normally I'm a data n' applications guy, but I love these in depth posts, especially when the papers remind me of all the things I studied at my [alma mater](http://www.biostat.washington.edu/).
  2. I am one of those people who only knows a tiny bit about Docker, but hears about it all the time. That being said, after I read about [Rocker](http://dirk.eddelbuettel.com/blog/2014/10/23/#introducing_rocker), I got pretty excited.
  3. Hadley W.'s [favorite tools](https://www.biostars.org/p/115481/), seems like that dude likes R Studio for some reason....(me too)
  4. [A cool visualization](http://priorprobability.com/2014/10/22/chess-piece-survival-rates/) of chess piece survival rates.
  5. [A short movie by 538](http://espn.go.com/video/clip?id=11694550) about statistics and the battle between Deep Blue and Gary Kasparov. Where's the popcorn?
  6. Twitter engineering released an R package for [detecting outbreaks](https://blog.twitter.com/2014/breakout-detection-in-the-wild). I wonder how [circular binary segmentation](http://www.bioconductor.org/packages/release/bioc/html/DNAcopy.html) would do?

&nbsp;

&nbsp;
