---
title: The Leek group guide to genomics papers
author: Jeff Leek
date: '2014-10-08'
output:
  distill::distill_article:
    self_contained: no
---

[Leek group guide to genomics papers](https://github.com/jtleek/genomicspapers/)

When I was a student, my advisor, [John Storey](http://www.genomine.org/), made a list of papers for me to read on nights and weekends. That list was incredibly helpful for a couple of reasons.

<ul class="task-list">
  <li>
    It got me caught up on the field of computational genomics
  </li>
  <li>
    It was expertly curated, so it filtered a lot of papers I didn't need to read
  </li>
  <li>
    It gave me my first set of ideas to try to pursue as I was reading the papers
  </li>
</ul>

I have often thought I should make a similar list for folks who may want to work wtih me (or who want to learn about statistial genomics). So this is my first attempt at that list. I've tried to separate the papers into categories and I've probably missed important papers. I'm happy to take suggestions for the list, but this is primarily designed for people in my group so I might be a little bit parsimonious.

&nbsp;
