---
title: 'Confession: I sometimes enjoy reading the fake journal/conference spam'
author: Rafael Irizarry
date: '2014-04-30'
output:
  distill::distill_article:
    self_contained: no
---

<p style="text-align: left">
  I've spent a considerable amount of time setting up filters to avoid getting spam from fake <a href="http://www.nytimes.com/2013/04/08/health/for-scientists-an-exploding-world-of-pseudo-academia.html?pagewanted=all">journals and conferences. </a>Unfortunately, they are exceptionally good at thwarting my defenses. This does not annoy me as much as I pretend because, secretly, I enjoy reading some of these emails. Here are three of my favorites.
</p>

<p style="text-align: left">
  1) Over-the-top robot:
</p>

> <p style="text-align: left">
>   <span style="font-style: italic">It gives us immense pleasure to invite you and your research allies to submit a manuscript for the journal “REDACTED”. The expertise of you in the never ending field of Gene Technology is highly appreciable. The level of intricacy shown by you in your work makes us even more proud, and </span><strong style="font-style: italic">we believe that your works should be known to mankind of science.</strong>
> </p>

2) Sarcastic robot?

> First of all, congratulations on the publication of your highly cited original article < The human colon cancer methylome shows similar hypo- and hypermethylation at conserved tissue-specific CpG island shores > in the field of colon cancer, **which has been cited more than 1 times and is in the world's top one percent of papers**. Such high number of citations reflects the high quality and influence of your paper.

<div>
  <p>
    3) Intimidating robot:
  </p>
  
  <blockquote>
    <p>
      This is Rocky.... Recently we have mailed you about the details of the conference. But we still have not received your response. So today we contact you again.
    </p>
  </blockquote>
  
  <p>
    NB: Although I am joking in this post, I do think these fake journals and conferences are a very serious problem. The fact that they are still around means enough money (mostly taxpayer money) is being spent to keep them in business. If you want to learn more, <a href="http://scholarlyoa.com/">this blog</a> does a good job on reporting on them and includes a <a href="http://scholarlyoa.com/publishers/">list of culprits.</a>
  </p>
</div>
