---
title: Not teaching computing and statistics in our public schools will make upward
  mobility even harder
author: Rafael Irizarry
date: '2014-01-29'
output:
  distill::distill_article:
    self_contained: no
---

In his book <a href="http://www.amazon.com/dp/0525953736/?tag=slatmaga-20" target="_blank">Average Is Over</a>, Tyler Cowen predicts that as automatization becomes more common, modern economies will eventually be composed of two groups: [1) a highly educated minority involved in the production of  automated services and 2) a vast majority earning very little but enough to consume some of the low-priced products created by group 1](http://en.wikipedia.org/wiki/Average_is_Over).  Not everybody will agree with this view, but we can't ignore the fact that automatization has already eliminated many middle class jobs in, for example, manufacturing and the automotive industries. New technologies, such as [driverless cars](http://www.youtube.com/watch?v=cdgQpa1pUUE) and online retailers, will very likely eliminate many more jobs (e.g. drivers and retail clerks) than they create (programmers and engineers).

Computer literacy is essential for working with automatized systems. Programming and learning from data are perhaps the most useful skill for creating these systems. Yet the current default curriculum includes neither computer science nor statistics. At the same time, there are plenty of resources for motivated parents with means to get their children to learn these subjects. Kids whose parents don't have the wherewithal to take advantage of these educational resources will be at an even greater disadvantage than they are today. This disadvantage is made worse by the fact that many of the aforementioned resources are free and open to the world  ([Codeacademy](http://www.codecademy.com/), [Khan Academy](https://www.khanacademy.org/), [EdX](https://www.edx.org/), and [Coursera](https://www.coursera.org/) for example) which means that a large pool of students that previously had no access to this learning material will also be competing for group 1 jobs. If we want to level the playing field we should start by updating the public school curriculum so that, in principle, everybody has the opportunity to compete.
