---
title: Help me find the good JSM talks
author: Admin
date: '2012-07-19'
output:
  distill::distill_article:
    self_contained: no
---

I&#8217;m about to head out for JSM in a couple of weeks. The sheer magnitude of the conference means it is pretty hard to figure out what talks I should attend. One approach I&#8217;ve used in the past is to identify people who I know give good talks and go to their talks. But that isn&#8217;t a very good talk-discovery mechanism. So this year I&#8217;m trying a crowd-sourcing experiment. 

First, some background on what kind of talks I like.

  * I strongly prefer talks where someone is tackling a problem presented by a new kind of data, whether they got that data from a collaborator, they scraped it off the web, or they generated it themselves.
  *  I am 100% ok if they only used linear regression to analyze the data if it led to interesting exploratory analysis, surprising results, or a cool conclusion. 
  * Major bonus points if the method is being used to solve a real-world problem.
  * I also really like creative and informative plots.
  * I prefer pictures to text/equations in general

On the other hand, I really am not a fan of talks where someone developed a method, no matter how cool, then started looking around for a data set to apply it to. 

If you know of anyone who is going to give a talk like that can you post it in the comments or tweet it to @simplystats with the hashtag #goodJSMtalks?

Also, if you know anyone who gives posters <a href="http://www.bioinformaticszen.com/post/genotype-from-phenotype/" target="_blank">like this</a>, lemme know so I can drop by.  

Thanks!!!
