---
title: Profile of Hilary Parker
author: Roger Peng
date: '2016-01-14'
output:
  distill::distill_article:
    self_contained: no
---

If you've ever wanted to know more about my [Not So Standard Deviations](https://soundcloud.com/nssd-podcast) co-host (and Johns Hopkins graduate) Hilary Parker, you can go check out the [great profile of her](http://thisisstatistics.org/hilary-parker-gets-crafty-with-statistics-in-her-not-so-standard-job/) on the American Statistical Association's This Is Statistics web site.

> **What advice would you give to high school students thinking about majoring in statistics?**
> 
> It’s such a great field! Not only is the industry booming, but more importantly, the disciplines of statistics teaches you to think analytically, which I find helpful for just about every problem I run into. It’s also a great field to be interested in as a generalist– rather than dedicating yourself to studying one subject, you are deeply learning a set of tools that you can apply to any subject that you find interesting. Just one glance at the topics covered on The Upshot or 538 can give you a sense of that. There’s politics, sports, health, history… the list goes on! It’s a field with endless possibility for growth and exploration, and as I mentioned above, the more I explore the more excited I get about it.
