---
title: 'Not So Standard Deviations: Episode 5 - IRL Roger is Totally With It'
author: Roger Peng
date: '2015-12-03'
output:
  distill::distill_article:
    self_contained: no
---

I just posted Episode 5 of Not So Standard Deviations so check your feeds! Sorry for the long delay since the last episode but we got a bit tripped up by the Thanksgiving holiday.

In this episode, Hilary and I open up the mailbag and go through some of the feedback we've gotten on the previous episodes. The rest of the time is spent talking about the importance of reproducibility in data analysis both in academic research and in industry settings.

If you haven't already, you can subscribe to the podcast through [iTunes](https://itunes.apple.com/us/podcast/not-so-standard-deviations/id1040614570). Or you can use the [SoundCloud RSS feed](http://feeds.soundcloud.com/users/soundcloud:users:174789515/sounds.rss) directly.

Notes:

  * Hilary's [talk on reproducible analysis in production](https://youtu.be/7B3n-5atLxM) at the New York R Conference
  * Hilary's [Ignite presentation](https://youtu.be/zlSOckFpYqg) at Strata 2013
  * Roger's [talk on "Computational and Policy Tools for Reproducible Research"](https://youtu.be/aH8dpcirW1U) at the Applied Mathematics Perspectives Workshop in Vancouver, 2011
  * Duke Scandal [Starter Set](http://goo.gl/rEO5QD)
  * [Keith Baggerly's talk](https://youtu.be/7gYIs7uYbMo) on Duke Scandal
  * The [Web of Trust](https://goo.gl/RtpBZa)
  * [testdat](https://goo.gl/MlM0gu) R package

[Download the audio file for this episode](https://api.soundcloud.com/tracks/235689361/download?client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea&oauth_token=1-138878-174789515-deb24181d01af).

Or you can listen right here:
