---
title: AAAS S&amp;T Fellows for Big Data and Analytics
author: Roger Peng
date: '2013-08-30'
output:
  distill::distill_article:
    self_contained: no
---

Thanks to [Steve Pierson](https://twitter.com/ASA_SciPol) of the ASA for letting us know that the AAAS [Science and Technology Fellowship program](http://fellowships.aaas.org/02_Areas/02_index.shtml) has a new category for "[Big Data and Analytics](http://fellowships.aaas.org/02_Areas/02_index.shtml#data)". For those not familiar, AAAS organizes the S&T Fellowship program to get scientists involved in the policy-making process in Washington and at the federal agencies. In general, the requirements for the program are

> Applicants must have a PhD or an equivalent doctoral-level degree at the time of application. Individuals with a master's degree in engineering and at least three years of post-degree professional experience also may apply. Some programs require additional experience. Applicants must be U.S. citizens. Federal employees are not eligible for the fellowships.

Further details are on the [AAAS web site](http://fellowships.aaas.org/04_Become/04_Eligibility.shtml).

I've met a number of current and former AAAS fellows working on Capitol Hill and at the various agencies and I have to say I've been universally impressed. I personally think getting more scientists into the federal government and involved with the policy-making process is a Good Thing. If you're a statistician looking to have a different kind of impact, this might be for you.
