---
title: Developing the New York Times Visual Election Outcome Explorer
author: Roger Peng
date: '2012-11-21'
output:
  distill::distill_article:
    self_contained: no
---

Mike Bostock [talks about the design and construction](http://source.mozillaopennews.org/en-US/articles/nyts-512-paths-white-house/) of the "[512 Paths to the White House](http://www.nytimes.com/interactive/2012/11/02/us/politics/paths-to-the-white-house.html)" visualization for the New York Times. I found this visualization extremely useful on election night as it helped me understand the implications of each of the swing state calls as the night rolled on.

Regarding the use of outside information to annotate the graphic:

> Applying background knowledge to give the data greater context—such as the influence of the auto-industry bailout on Ohio’s economy—makes the visualization that much richer. After all, visualizations aren’t just about numbers, but about understanding the world we live in; qualitative information can add substantially to a quantitative graphic.

While the technical details are fascinating, I was equally interested in the editorial decisions they had to make to build a usable visualization.
