---
title: Postdoctoral fellow position in reproducible research
author: Roger Peng
date: '2013-03-14'
output:
  distill::distill_article:
    self_contained: no
---

We are looking to recruit a postdoctoral fellow to work on developing tools to make scientific research more easily reproducible. We're looking for someone who wants to work on (and solve!) real research problems in the biomedical sciences and address the growing need for reproducible research tools. The position would be in the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health and would be jointly advised by Jeff and myself.

**Qualifications**: PhD in statistics, biostatistics, computer science, or related field; strong programming skills in R and Perl/Python/C; excellent written and oral communication skills; serious moxie

**Additional Information**: Informal questions about the position can be sent to Dr. Roger Peng at rpeng @ jhsph.edu. Applications will be considered as they arrive.

<div title="Page 1">
  <p>
    To apply, send a cover letter describing your research interests and interest in the position, a CV, and the names of three references. In your application, please reference "Reproducible Research postdoctoral fellowship". Application materials should be emailed to Dr. Roger Peng at rpeng @ jhsph.edu.
  </p>
  
  <p>
    Applications from minority and female candidates are especially encouraged. Johns Hopkins University is an AA/EOE.
  </p>
</div>
