---
title: Crowdsourcing resources for the Johns Hopkins Data Science Specialization
author: Jeff Leek
date: '2014-08-15'
output:
  distill::distill_article:
    self_contained: no
---

<p style="color: #222222;">
  Since we began offering the <a href="https://www.coursera.org/specialization/jhudatascience/1">Johns Hopkins Data Science Specialization</a> we've noticed the unbelievable passion that our students have about our courses and the generosity they show toward each other on the course forums. Many students have created quality content around the subjects we discuss, and many of these materials are so good we feel that they should be shared with all of our students. We also know there are tons of other great organizations creating material (looking at you <a href="http://software-carpentry.org/">Software Carpentry folks</a>).
</p>

<p style="color: #222222;">
  We're excited to announce that we've created a site using GitHub Pages: <a style="color: #1155cc;" href="http://datasciencespecialization.github.io/" target="_blank">http://<wbr />datasciencespecialization.<wbr />github.io/</a> to serve as a directory for content that the community has created. If you've created materials relating to any of the courses in the Data Science Specialization please send us a pull request and we will add a link to your content on our site. You can find out more about contributing here: <a style="color: #1155cc;" href="https://github.com/DataScienceSpecialization/DataScienceSpecialization.github.io#contributing" target="_blank">https://github.com/<wbr />DataScienceSpecialization/<wbr />DataScienceSpecialization.<wbr />github.io#contributing</a>
</p>

<p style="color: #222222;">
  We can't wait to see what you've created and where the community can take this site!
</p>

<p style="color: #222222;">
  <p style="color: #222222;">
