---
title: Sunday data/statistics link roundup (7/28/13)
author: Jeff Leek
date: '2013-07-28'
output:
  distill::distill_article:
    self_contained: no
---

  1. <span style="line-height: 16px;"><a href="http://www.huffingtonpost.com/2013/07/23/women-in-physics-statistics-hiring-bias-female-faculty_n_3635710.html">An article</a> in the Huffpo about a report claiming there is no gender bias in the hiring of physics faculty. I didn't read the paper carefully but  I definitely agree with the quote from  Prof. Dame Athene Donald that the comparison should be made to the number of faculty candidates on the market. I'd also be a little careful about touting my record of gender equality if only 13% of faculty in my discipline were women (via Alex N.).</span>
  2. If you are the only person who hasn't seen the upwardly mobile by geography article yet, [here it is](http://www.nytimes.com/2013/07/22/business/in-climbing-income-ladder-location-matters.html?hp&_r=1&) (via Rafa). Also covered over at the great "[charts n things](http://chartsnthings.tumblr.com/post/56193905994/winning)" blog.
  3. Finally [some good news](http://news.sciencemag.org/scientific-community/2013/07/senate-panel-gives-nsf-8-budget-boost) on the science funding front; a Senate panel raises NSF's budget by 8% (the link worked for me earlier but I was having a little trouble today). I think that this is of course a positive development. I think that article pairs very well with [this provocative piece](http://www.businessinsider.com/a-private-university-might-have-saved-detroit-2013-7) suggesting Detroit might have done better if they had a private research school.
  4. I'm going to probably talk about this more later in the week because it gets my blood pressure up, but I thought I'd just say again that [hyperbolic takedowns](http://andrewgelman.com/2013/07/24/too-good-to-be-true-the-scientific-mass-production-of-spurious-statistical-significance/) of the statistical methods in specific papers in the popular press [leads only one direction](http://simplystatistics.org/2013/05/06/why-the-current-over-pessimism-about-science-is-the-perfect-confirmation-bias-vehicle-and-we-should-proceed-rationally/).
