---
title: 'Simply Statistics #JSM2013 Picks for Monday'
author: Roger Peng
date: '2013-08-05'
output:
  distill::distill_article:
    self_contained: no
---

I'm sadly not able to attend the Joint Statistical Meetings this year (where Nate Silver is the keynote speaker!) in the great city of Montreal. I'm looking forward to checking out the chatter on #JSM2013 but in the meantime, here are the sessions I would have attended if I'd been there. If I pick more than one session for a given time slot, I assume you can run back and forth between the two.

  * 8:30-10:20am: Kasper Hansen is presenting in **Statistical Methods for High-Dimensional Data: Presentations by Junior Researchers** (CC-515c) and there are some great people in **The Profession of Statistics and Its Impact on the Media** (CC-516d)
  * 10:30am-12:20pm: There are some heavy hitters in the **Showcase of Analysis of Correlated Measurements** (CC-511d); this session has a great title **Herd Immunity: Teaching Techniques for the Health Sciences **(CC-515b)**
  
** 
  * 2-3:50pm: I have a soft spot in my heart for a good MCMC session like **Challenges in Using Markov Chain Monte Carlo in Modern Applications** (CC-510d); I also have a soft spot for visualization and Simon Urbanek - **Visualizing Big Data Interactively **(CC-510b)
  * 4-5:50pm: I would check out Nate Silver's talk (CC-517ab)

Have fun!
