---
title: Genomics Case Studies Online Courses Start in Two Weeks (4/27)
author: Rafael Irizarry
date: '2015-04-13'
output:
  distill::distill_article:
    self_contained: no
---

The last month of the [HarvardX Data Analysis for Genomics series](http://genomicsclass.github.io/book/pages/classes.html) start on 4/27. We will cover case studies on RNAseq, Variant calling, ChipSeq and DNA methylation. Faculty includes Shirley Liu, Mike Love, Oliver Hoffman and the HSPH Bioinformatics Core. Although taking the previous courses on the series will help, the four case study courses were developed as stand alone and you can obtain a certificate for each one without taking any other course.

Each course is presented over two weeks but will remain open until June 13 to give students an opportunity to take them all if they wish. For more information follow the links listed below.

  1. [RNA-seq data analysis](https://www.edx.org/course/case-study-rna-seq-data-analysis-harvardx-ph525-5x) will be lead by Mike Love
  2. [Variant Discovery and Genotyping](https://www.edx.org/course/case-study-variant-discovery-and-genotyping-harvardx-ph525-6x) will be taught by Shannan Ho Sui, Oliver Hofmann, Radhika Khetani and Meeta Mistry (from the The HSPH Bioinformatics Core)
  3. [ChIP-seq data analysis](https://www.edx.org/course/case-study-chip-seq-data-analysis-harvardx-ph525-7x) will be lead by Shirley Liu
  4. [DNA methylation data analysis](https://www.edx.org/course/case-study-dna-methylation-data-analysis-harvardx-ph525-8x) will be lead by Rafael Irizarry
