---
title: Announcing the JHU Data Science Hackathon 2015
author: Roger Peng
date: '2015-07-28'
output:
  distill::distill_article:
    self_contained: no
---

We are pleased to announce that the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health will be hosting the first ever [JHU Data Science Hackathon](https://www.regonline.com/jhudash) (DaSH) on **September 21-23, 2015** at the Baltimore Marriott Waterfront.

This event will be an opportunity for data scientists and data scientists-in-training to get together and hack on real-world problems collaboratively and to learn from each other. The DaSH will feature data scientists from government, academia, and industry presenting problems and describing challenges in their respective areas. There will also be a number of networking opportunities where attendees can get to know each other. We think this will be  fun event and we encourage people from all areas, including students (graduate and undergraduate), to attend.

To get more details and to sign up for the hackathon, you can go to the [DaSH web site](https://www.regonline.com/jhudash). We will be posting more information as the event nears.

Organizers:

  * Jeff Leek
  * Brian Caffo
  * Roger Peng
  * Leah Jager

Funding:

  * National Institutes of Health
  * Johns Hopkins University

&nbsp;
