---
title: 'If I were at #ENAR2013 today, here''s where I''d go'
author: Roger Peng
date: '2013-03-12'
output:
  distill::distill_article:
    self_contained: no
---

This week is the annual ENAR meeting, the big biostatistics conference, in Orlando, Florida. It actually started on Sunday but I haven't gotten around to looking at the program (obviously, I'm not there right now). Flipping through the [program](http://www.enar.org/meetings2013/2013_program.pdf) now, here's what looks good to me for Tuesday:

  * <span style="line-height: 16px">8:30-10:15am: <strong>Functional Neuroimaging Decompositions</strong>, Grand Ballroom 3 </span>
  * 10:30am-12:15pm: Hmm...I guess you should go to the **Presidential Invited Address**, Grand Ballroom 7
  * 1:45-3:30pm: **JABES Showcase**, Grand Ballroom 8A; **Statistical Body Language: Analytical Methods for Wearable Computing**, Grand Ballroom 4
  * 3:45-5:30pm: **Big Data: Wearable Computing, Crowdsourcing, Space Telescopes, and Brain Imaging**, Grand Ballroom 8A; **Sample Size Planning for Clinical Development**, Grand Ballroom 6

That's right, you can pack in _two_ sessions on wearable computing today if you want. I'll post tomorrow for what looks good on Wednesday.
