---
title: Help needed for establishing an ASA statistical genetics and genomics section
author: Rafael Irizarry
date: '2013-09-12'
output:
  distill::distill_article:
    self_contained: no
---

To promote research and education in statistical genetics and genomics, some of us in the community would like to establish a statistical genetics and genomics section of the American Statistical Association (ASA). Having an ASA section gives us certain advantages, such as having allocated invited sessions at JSM, young investigator and student awards, and senior investigator awards in statistical genetics and genomics, as well as a community to interact and exchange information.

We need at least 100 ASA members  to pledge that they will join the section (if you are in more than 3 sections already you will be asked to pay a nominal fee of less than $10). If you are interested please fill a row in the following google doc by November 1st:

<a href="https://docs.google.com/spreadsheet/ccc?key=0AtD3gd8kGN45dE9BZ1pTYWtCa0M2VWhKckRoUE9KLVE#gid=0" target="_blank">https://docs.google.com/<wbr />spreadsheet/ccc?key=<wbr />0AtD3gd8kGN45dE9BZ1pTYWtCa0M2V<wbr />WhKckRoUE9KLVE#gid=0</a>
