---
title: The time traveler's challenge.
author: Jeff Leek
date: '2014-03-19'
output:
  distill::distill_article:
    self_contained: no
---

_Editor's note: This has nothing to do with statistics. _

I do a lot of statistics for a living and would claim to know a relatively large amount about it. I also know a little bit about a bunch of other scientific disciplines, a tiny bit of engineering, a lot about pointless sports trivia, some current events, the geography of the world (vaguely) and the geography of places I've lived (pretty well).

I have often wondered, if I was transported back in time to a point before the discovery of say, how to make a fire, how much of human knowledge I could recreate. In other words, what would be the marginal effect on the world of a single person (me) being transported back in time. I could propose Newton's Laws, write down a bunch of the basis of calculus, and discover the central limit theorem. I probably couldn't build an internal combustion engine - I know the concept but don't know enough of the details. So the challenge is this.

_ If you were transported back 4,000 or 5,000 years, how much could you accelerate human knowledge?_

When I told Leah J. about this idea she came up with an even more fascinating variant.

_Suppose that I told you that in 5 days you were going to be transported back 4,000 or 5,000 years but you couldn't take anything with you. What would you read about on Wikipedia? _
