---
title: Introduction to Bioconductor HarvardX MOOC starts this Monday March 30
author: Rafael Irizarry
date: '2015-03-24'
output:
  distill::distill_article:
    self_contained: no
---

Bioconductor is one of the most widely used open source toolkits for biological high-throughput data. In this four week course, co-taught with Vince Carey and Mike Love, we will introduce you to Bioconductor's general infrastructure and then focus on two specific technologies: next generation sequencing and microarrays. The lectures and assessments will be annotated in case you want to focus only on one of these two technologies. Although if you plan to be a bioinformatician we recommend you learn both.

Topics covered include:

  * A short introduction to molecular biology and measurement technology
  * An overview on how to leverage the platform and genome annotation packages and experimental archives
  * GenomicsRanges: the infrastructure for storing, manipulating and analyzing next generation sequencing data
  * Parallel computing and cloud concepts
  * Normalization, preprocessing and bias correction.
  * Statistical inference in practice: including hierarchical models and gene set enrichment analysis
  * Building statistical analysis pipelines of genome-scale assays including the creation of reproducible reports

Throughout the class we will be using data examples from both next generation sequencing and microarray experiments.

We will assume [basic knowledge of Statistics and R](https://www.edx.org/course/statistics-r-life-sciences-harvardx-ph525-1x).

For more information visit the [course website](https://www.edx.org/course/introduction-bioconductor-harvardx-ph525-4x).
