---
title: Pro Tips for Grad Students in Statistics/Biostatistics (Part 1)
author: Admin
date: '2012-06-18'
output:
  distill::distill_article:
    self_contained: no
---

<div>
  I just finished teaching a Ph.D. level applied statistical methods course here at Hopkins. As part of the course, I gave one &#8220;pro-tip&#8221; a day; something I wish I had learned in graduate school that has helped me in becoming a practicing applied statistician. Here are the first three, more to come soon. 
</div>

  1. A major component of being a researcher is knowing what&#8217;s going on in the research community. Set up an RSS feed with journal articles. Google Reader is a good one, but there are others. Here are some good applied stat journals: Biostatistics, Biometrics, Annals of Applied Statistics&#8230;
  2. Reproducible research is a hot topic, in part because a couple of high-profile papers that were disastrously non-reproducible (see &#8220;<a href="http://projecteuclid.org/DPubS?service=UI&version=1.0&verb=Display&handle=euclid.aoas/1267453942" target="_blank">Deriving chemosensitivity from cell lines: Forensic bioinformatics and reproducible research in high-throughput biology</a>&#8221;). When you write code for statistical analysis try to make sure that: (a) It is neat and well-commented - liberal and specific comments are your friend. (b)That it can be run by someone other than you, to produce the same results that you report.
  3. In data analysis - particularly for complex high-dimensional  
    data - it is frequently better to choose simple models for clearly defined parameters. With a lot of data, there is a strong temptation to go overboard with statistically complicated models; the danger of overfitting/ over-interpreting is extreme. The most reproducible results are often produced by sensible and statistically &#8220;simple&#8221; analyses (Note: being sensible and simple does not always lead to higher prole results).
