---
title: Statistician (@cocteau) to show journalists how it's done
author: Admin
date: '2012-07-29'
output:
  distill::distill_article:
    self_contained: no
---

Mark Hansen, a Professor at UCLA&#8217;s Departments of Statistics and Media Arts, has been appointed as the inaugural Director of the <a href="http://www.journalism.columbia.edu/news/609" target="_blank">David and Helen Gurley Brown Institute for Media Innovation</a>. The Institute is a joint venture between Columbia University&#8217;s Graduate School of Journalism and Stanford&#8217;s School of Engineering.

> <span>The Institute and the collaboration between the two schools is groundbreaking in that it is designed to encourage and support new endeavors with the potential to inform and entertain in transformative ways. It will recognize the increasingly important connection between journalism and technology, bringing the best from the East and West Coasts.</span>

<span>Congratulations to Mark for this fantastic opportunity!</span>
