---
title: Samuel Kou wins COPSS Award
author: Admin
date: '2012-08-06'
output:
  distill::distill_article:
    self_contained: no
---

At JSM this year we learned that <a href="http://www.people.fas.harvard.edu/~skou/" target="_blank">Samuel Kou</a> of Harvard&#8217;s Department of Statistics won the Committee of Presidents of Statistical Societies (<a href="http://nisla05.niss.org/copss/?q=copss" target="_blank">COPSS</a>) President&#8217;s award. The award is given annually to

> <span>a young member of the statistical community in recognition of an outstanding contribution to the profession of statistics. </span><span>The recipient of the Presidents&#8217; Award must be a member of at least one of the participating societies. The candidate may be chosen for a single contribution of extraordinary merit, or an outstanding aggregate of contributions, to the profession of statistics.</span><span> </span>

Samuel&#8217;s work spans a wide range of areas from biophysics to MCMC to model selection with contributions in the top journals in statistics and elsewhere. He is also a member of a highly selective group of people who have been promoted to full Professor at Harvard&#8217;s Department of Statistics. (Bonus points to those who can name the last person to achieve such a distinction.)

This is a well-deserved honor to an exemplary member of our field.
